### ISSUE TITLE
Few issues noticed on the Arch - at a glance

### ISSUE THREAD

**Issue by cybernth** [Tendrl/documentation#101]
1. Grafana alerts are processed by monitoring-integration and not by notifier
2. Node-agent also runs on server node
3. gluster-integration directly communicates with etcd as well. Only logging/alert are passed through node-agent
4. monitoring-integration also talks to graphite(for aggregated data) and grafana(dashboard creation)

https://github.com/Tendrl/documentation/blob/master/tendrl-with-gluster-architecture-overview.adoc

**Comment by julienlim** [comment]
@nthomas-redhat @r0h4n @mbukatov @jjkabrown1 @rghatvis@redhat.com 

I've updated the diagram and accompanying notes per your comment.  See below:

With regards to node-agent running on server node the node agent is in the green and yellow are to indicate it runs on the server node.  However, I've made it clearer in the bullets on the right.

Can you please review these updates before I commit the changes?  Thanks.

![tendrl architecture diagram at-a-glance 1](https://user-images.githubusercontent.com/5589919/37728129-d9686c4e-2d0f-11e8-9188-870a965a30fa.png)

**Comment by julienlim** [comment]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1536376

**Comment by cybernth** [comment]
The link from grafana to notifier needs to be removed.
the connection between MI and grafana should be on both directions.

UI->Grafana, its just URL redirection, should really need to show that?

Rest looks fine to me

@julienlim

**Comment by GowthamShanmugam** [comment]
grafana -> notifier link is not required
Actually it works like:
  1. grafana -> monitoring-integration -> node-agent -> etcd    then
  2. notifier -> etcd also
  3. notifier -> node-agent also possible to push log_messages into node-socket. (to log messages)

**Comment by julienlim** [comment]
@nthomas-redhat @GowthamShanmugam 

I've updated the diagram per your comments -- see below.  Please review/comment.  Thanks.

![tendrl architecture diagram at-a-glance 2](https://user-images.githubusercontent.com/5589919/37781461-21f726dc-2dc7-11e8-9aed-42bf962a6832.png)

**Comment by julienlim** [comment]
Submitted PR: https://github.com/Tendrl/documentation/pull/102

**Comment by GowthamShanmugam** [comment]
LGTM

**Comment by julienlim** [comment]
Merged, so closing this issue.
