### ISSUE TITLE
Tendrl HA

### ISSUE THREAD

**Issue by cybernth** [Tendrl/documentation#12]
Need to have a clarity on how we are planning to achieve HA in Tendrl

**Comment by sankarshanmukhopadhyay** [comment]
@nthomas-redhat - are you looking at high availability of the Tendrl services or, just resiliency of the state? I ask this to attempt to achieve a distinction between using standard HA practices to have Tendrl service end point migration as against a resilient state store.

**Comment by cybernth** [comment]
@sankarshanmukhopadhyay  - I understand that central store(etcd) provide clustering which makes it resilient data store. But my question is more around HA of Tedrl services.
1. There are multiple Tendrl App instances running. Are they know each other and fail-over if one of them fails? I am coming from scenario where the UI is connected to one of the instance and what happens if that fails?
2. I assume that etcd has inbuilt support for clustering and HA. That means connection between Tendrl App and etcd instance will be transferred to the healthy one in case of a failure to the existing etcd instance?
