### ISSUE TITLE
Tendrl App

### ISSUE THREAD

**Issue by cybernth** [Tendrl/documentation#13]
1. Language used for implementation?
2. HTTP server used?
3. API spec?
4. How the job queue is constructed?
5. Planning to use any web framework?

**Comment by shtripat** [comment]
In addition to above ones I have few as below
1. Does tendrl app need to have SDS specific logic, as it directly talks to central store and central store might be having SDS specific data maintained. How is it planned to be tackled

**Comment by anupnivargi** [comment]
@nthomas-redhat here are my thoughts about your questions
1. We are using Ruby with Sinatra Web framework with the etcd-client to connect to etcd.
2. We have not decided anything about the deployment but a ideal deployment would be Puma as application server and Apache as web server.
3. We have written a basic overview for the API, refer https://github.com/Tendrl/tendrl/pull/2 you can comment on the PR if you have any inputs.
4. For every POST/PUT/DELETE action a job is created in the etcd queue with the required parameters, which is picked up by agents/bridge depending on the job and processed and  updated. 
5. There are multiple frameworks in Ruby for building Web applications like Rails, Sinatra or Padrino, but we have decided to use Sinatra which gives us a clean slate and let's us pick and choose how we want to solve the domain problem.

@shtripat The Tendrl app will have all the logic coming from the operations and states yaml files, using which we will build the API's and its behaviour. The operations and states files are Ceph and Gluster versions specific, so we know what operations and actions can be performed on each version of the storage provider.

**Comment by r0h4n** [comment]
Issue too old, closing.
