### ISSUE TITLE
User Management in Tendrl

### ISSUE THREAD

**Issue by cybernth** [Tendrl/documentation#14]
- Local
  - AD/LDAP/IPA integration

Need to document the high level plan.

**Comment by mbukatov** [comment]
We need to make sure that the plan is discussed with [FreeIPA](http://www.freeipa.org/page/Main_Page) people.

**Comment by brainfunked** [comment]
The real question for me is whether _user_ management needs to be in the API or in the UI. The API is aimed at systems integration, so it should have more generalised permissions as opposed to the UI, which could handle user authentication.

**Comment by japplewhite** [comment]
Optional Keystone integration might make some sense, especially since LDAP/AD can be a back end for Keystone and integration with OpenStack is an obvious integration point. The same approach to presenting a valid ticket for API access could be leveraged. May be overly complicated though.

**Comment by r0h4n** [comment]
Old issue, file new one if required.
