### ISSUE TITLE
Atomicity of operations executed by Tendrl

### ISSUE THREAD

**Issue by cybernth** [Tendrl/documentation#15]
How to ensure the atomicity of critical operations? Suppose there is an cluster creation operation in progress with a number of storage nodes, its not desirable that another user attempting a similar operation with same set of nodes. How to prevent this? Does the central store provides any mechanism? or Tendrl supposed to have some lock framework implemented?

**Comment by r0h4n** [comment]
Closing, please create new issue with relevant context
