### ISSUE TITLE
Document the different vim/editor specific configurations for development environment

### ISSUE THREAD

**Issue by shtripat** [Tendrl/documentation#18]
If there are specific guidelines for using editor like Atom/vim, better publish the configurations needed to be done with examples.

**Comment by r0h4n** [comment]
Tendrl's styling is checked via "tox -epep8" command from root of the git repo.

More info here: https://github.com/Tendrl/bridge_common/blob/master/HACKING.rst

**Comment by shtripat** [comment]
For a newbie in python, it would better if we suggest some .vimrc and say Atom editor specific settings to by default take care of few of the guidelines imposed by pep8 (whatever is possible at least). Thats what I mean here.

**Comment by sankarshanmukhopadhyay** [comment]
@shtripat - the drawback of trying to "recommend" a set of editors is that often it tends to put off contributions. Is this a hard drawback or, a "good to have", given that the developers are familiar with how to set up the editor to handle pep8 and such. For example, http://docs.python-guide.org/en/latest/dev/env/
