### ISSUE TITLE
Detailed explanation for tendrl agent on storage nodes

### ISSUE THREAD

**Issue by shtripat** [Tendrl/documentation#20]
Looking at the architecture diagram still not very clear if we still are planning to use collectd or some new tool to take care of various time series data collections and push to time series DB.

Also not clear on what time series DB and monitoring system as such suggested / planned in the system.

**Comment by sankarshanmukhopadhyay** [comment]
@shtripat I would recommend that we undertake the following:
- do a quick assessment of the time-series/trending model adopted for Skyring and provide read-out to tendrl-devel
- the monitoring piece is multi-part; working with SNMP traps and design, implementation of the receiver which subscribes to the hooks

Having said that, the good thing to do here is provide input/feedback/insights to the tendrl-devel list based on existing knowledge and awareness of these systems.

**Comment by mbukatov** [comment]
Any update here?

**Comment by mbukatov** [comment]
Related to https://github.com/Tendrl/documentation/issues/61

**Comment by r0h4n** [comment]
Closing this one, too old, open new issue with relevant context
