### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by jcsp** [Tendrl/documentation#23]
What is the security model?
- How does Tendrl establish mutual trust with nodes?
- How are users authenticated and user permissions managed?
- What crypto is used?

**Comment by mbukatov** [comment]
Any update here?

**Comment by r0h4n** [comment]
Closing this one, open new issue if required with relevant context

- tendrl-node-agent have no mutual trust, they all talk to central store and not to each other
- Check tendrl-api for user auth and permissions (https://github.com/Tendrl/api/blob/master/docs/users.adoc)
