### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by jcsp** [Tendrl/documentation#24]
How does Tendrl scale to managing systems with many thousands of nodes?
- What is the ballpark number of Central Store transactions per second per node or per OSD?
- What is the ballpark transactions per second limit of the Central Store?
- How does the system behave if nodes are sending updates faster than the store can persist them?
- On a busy system, what takes priority, writes from the node side or queries from the UI side?

**Comment by r0h4n** [comment]
- transactions (meaning http api calls to etcd) depends on the type of deployment you have for etcd itself (https://coreos.com/etcd/docs/latest/op-guide/hardware.html)

- How does the system behave if nodes are sending updates faster than the store can persist them?
 The system fails 

- On a busy system, what takes priority, writes from the node side or queries from the UI side?
There's no priority as such
