### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by jcsp** [Tendrl/documentation#26]
I note on Tendrl Core Components that there are multiple "Tendrl Application Instance" entities.  When they are handling incoming requests that modify the same storage resources, how is consistency guaranteed?

Is there a requirement that the Central Store provides some level of transactional access across different pieces of data?

A worked example would be useful.

**Comment by mbukatov** [comment]
This seems to be related to https://github.com/Tendrl/documentation/issues/12
