### ISSUE TITLE
Details about the clustering of central store.

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/documentation#27]
1. Where will the central store be located ? all the instances on same machine or will it span across multiple machines ?
2. Considering this to be a distributed data store, how many instances are we planning to have ? Will the number of instance be increased based on the number of nodes managed by Tendrl ?
3. how difficult/easy is it to deploy the central store, is it just package installation ? if not, which component will take care of deploying this ?

**Comment by brainfunked** [comment]
Central Store is etcd, so ther relevant etcd documentation has to be followed: https://coreos.com/etcd/docs/latest/clustering.html

**Comment by mbukatov** [comment]
This is related to both https://github.com/Tendrl/documentation/issues/61 (eg. the fact that *Central Store* means *etcd* is not directly stated anywhere in the documentation so far) and https://github.com/Tendrl/documentation/issues/12.
