### ISSUE TITLE
Analyze feasibility of ceph-mgr in tendrl and parity with calamari

### ISSUE THREAD

**Issue by shtripat** [Tendrl/documentation#28]
We understand that ceph-mgr might not be available readily for consumption in tendrl. But need to analyze the feasibility of using ceph-mgr in tendrl stack.
The items to be checked -
1. How easy/tough it is to setup ceph-mgr
2. What is the deployment mechanism (whether on all the mons or on leader mon only) for ceph-mgr
3. What is parity of features from calamari
4. How feasible to integrate with tendrl-core

**Comment by jcsp** [comment]
To pre-empt the questions a bit:
- Today, running ceph-mgr in a development environment is just as simple as running the rest of ceph (it's integrated into vstart).  There is a separate pull request with RPM packages that hasn't been tested yet.  However, anyone doing development should definitely be using a locally built tree and not packages.
- The default deployment strategy will be to set up one ceph-mgr daemon alongside each ceph-mon daemon.
- The parts of the Calamari REST API that went via the mons are all still there.  The parts that did something out of band are gone (i.e. anything involving salt, the calamari DB's event table).  The legacy /v1 API is all gone.  All the URLs no longer include a /<fsid>/ part.  The /cli part is gone (could in principle be re-added)

**Comment by shtripat** [comment]
My comments in the respective order above
- Setting up dev environment using vstart for ceph-mgr and checking features etc is good enough. But to test its usability with say tendrl or any other client, we might need ceph-mgr running with mon nodes (guide me if I am wrong and if its already possible to do that by building and deploying the bits with mon nodes) so that tendrl can make calls to ceph-mgr and consume output. Please suggest..
- If all the mon nodes are going to have ceph-mgr running, is it like from tendrl or any other client we need to figure out the leader mon and submit calls to that for any queries and management actions. If that's the case if leader mon somehow goes down, a fallback to other mon would be required (leader re-election happens within ceph automatically I know). We have this kind of thing happening earlier with calamari-lite and finally it became like run calamari on one mon only and in case of failure fall back to different mon node and start calamari on that node and start using it. Is this understanding same with ceph-mgr as well? If not please throw some light on how to tackle this.
- I remember there were certain actions like rnd create/resize/delete and creation of say ec-profiles etc was not possible as is using individual REST end points in calamari-lite and so we had to use /cli end points. How to tackle these things with ceph-mgr?

I might be having more questions as I proceed further and would be posting here :)

**Comment by shtripat** [comment]
@jcsp is the API only way to communicate with ceph-mgr or we can use command line rados commands ? I hope yes but can you please confirm the same?

**Comment by jcsp** [comment]
@shtripat ceph-mgr modules can expose CLI commands (invoked using the `ceph` CLI or with librados), or their own protocols (such as the `rest` module).  So at a high level it is up to Tendrl, depends whether you want to buy into a REST API and work on improving that, or write a separate module.

**Comment by jcsp** [comment]
> Setting up dev environment using vstart for ceph-mgr and checking features etc is good enough. But to test its usability with say tendrl or any other client, we might need ceph-mgr running with mon nodes (guide me if I am wrong and if its already possible to do that by building and deploying the bits with mon nodes) so that tendrl can make calls to ceph-mgr and consume output. Please suggest..

Obviously once it's all nicely packaged you'll have that, but running against a vstart cluster shouldn't block you for now.

> If all the mon nodes are going to have ceph-mgr running, is it like from tendrl or any other client we need to figure out the leader mon and submit calls to that for any queries and management actions. If that's the case if leader mon somehow goes down, a fallback to other mon would be required (leader re-election happens within ceph automatically I know). We have this kind of thing happening earlier with calamari-lite and finally it became like run calamari on one mon only and in case of failure fall back to different mon node and start calamari on that node and start using it. Is this understanding same with ceph-mgr as well? If not please throw some light on how to tackle this.

No, you don't have to do any of that.  There was a discussion including Mrugesh while I was in Bangalore about how HA is handled.

ceph-mgr has a single daemon active at any time, and Ceph internally handles managing that.  How you deal with that as a client depends what protocol you're using.  If you're using REST you can either just try connecting to each mon node and see who is up, or you can look at "ceph status" to see which mgr is active and connect to that.  If you're using "ceph tell mgr ..." access, it handles finding who to send the command to.  If you're using some other protocol with a custom module, it's up to you.

> I remember there were certain actions like rnd create/resize/delete and creation of say ec-profiles etc was not possible as is using individual REST end points in calamari-lite and so we had to use /cli end points. How to tackle these things with ceph-mgr?

So in USM2 you were just using the Calamari /cli endpoint to do RBD stuff, right?  Internally, that was Calamari remoting to a mon node and running the command line tool for you.  So now, you can either go run the command line tools yourself, or call into librbd yourself, or you can look at exposing RBD stuff properly in either the `rest` module or in a special ceph-mgr module for tendrl.

**Comment by shtripat** [comment]
@jcsp I tried setting up dev environment and use ceph-mgr. My progress till now is as below
1. Cloned ceph repo
2. checked out ceph-mgr branch
3. Built ceph and ceph-mgr
4. Started ceph with manager using the command "MDS=1 MON=1 OSD=3 MGR=1 ../src/vstart.sh -n -d"

After this I see the ceph-mgr process running as shown below

$ ps -ef | grep ceph-mgr
shubhen+  9139     1  0 Sep22 ?        00:00:01 /home/shubhendu/work/ceph/build/bin/ceph-mgr -i x

But I dont see anything listening on port 8002 (as ceph-mgr should be listening on this like calamari)

$ netstat -na | grep 8002
$ 

Also while accessing the URL http://localhost:8002/api/v2/ it says "This site can't be reached".
Attached out/mgr.x.log for reference.
[mgr.x.log.txt](https://github.com/Tendrl/documentation/files/488920/mgr.x.log.txt)

Kindly suggest/help here.

**Comment by shtripat** [comment]
@jcsp I feel I am not heading much ahead. With a fresh setup I am able to run "./bin/ceph tell mgr osd perf" and it shows the below output

+----+----------------------------------+-------+-------+--------+---------+--------+---------+
| id |               host               |  used | avail | wr ops | wr data | rd ops | rd data |
+----+----------------------------------+-------+-------+--------+---------+--------+---------+
| 0  | dhcp35-52.lab.eng.blr.redhat.com |  129G |  247G |    0   |     0   |    0   |     0   |
| 1  | dhcp35-52.lab.eng.blr.redhat.com |  129G |  247G |    0   |     0   |    0   |     0   |
| 2  | dhcp35-52.lab.eng.blr.redhat.com |  129G |  247G |    0   |     0   |    0   |     0   |
+----+----------------------------------+-------+-------+--------+---------+--------+---------+

But REST api still not coming up. I would rather suggest having a BJ setup and show my setup.
Also other than out/mgr.x.log, can we try checking other log files to get some idea.

Kindly let me know your comfortable time for BJ (through personal mail), so I would ping you on this.

**Comment by shtripat** [comment]
@jcsp I feel I am not heading much ahead. With a fresh setup I am able to run "./bin/ceph tell mgr osd perf" and it shows the below output

+----+----------------------------------+-------+-------+--------+---------+--------+---------+
| id |               host               |  used | avail | wr ops | wr data | rd ops | rd data |
+----+----------------------------------+-------+-------+--------+---------+--------+---------+
| 0  | dhcp35-52.lab.eng.blr.redhat.com |  129G |  247G |    0   |     0   |    0   |     0   |
| 1  | dhcp35-52.lab.eng.blr.redhat.com |  129G |  247G |    0   |     0   |    0   |     0   |
| 2  | dhcp35-52.lab.eng.blr.redhat.com |  129G |  247G |    0   |     0   |    0   |     0   |
+----+----------------------------------+-------+-------+--------+---------+--------+---------+

But REST api still not coming up. I would rather suggest having a BJ setup and show my setup.
Also other than out/mgr.x.log, can we try checking other log files to get some idea.

Kindly let me know your comfortable time for BJ (through personal mail), so I would ping you on this.

**Comment by shtripat** [comment]
Thanks @jcsp for your time for one-on-one discussion. That was very helpful.

**Comment by shtripat** [comment]
After trying out ceph-mgr built from PR https://github.com/jcsp/ceph/tree/wip-ceph-mgr and trying out different REST apis and "ceph tell mgr" commands below is the summary of analysis.

## ceph-mgr - An Introduction

The ceph-mgr includes the core functionality for enabling python modules that provides service and exposes CLI hooks. It actually slashes out the persistent DB which calamari used to have, and rather get details like pgmap, OSD map, MDS map, performance counters etc directly from underlying OSD nodes of the cluster and maintains the details in memory. The client modules can have persistent piece of data which ceph-mgr stashes. The ceph-manager has got REST apis as well exposed, which could used as one protocol to talk to ceph-mgr backend.

The below block diagram tries to explain the architecture of ceph-mgr

![ceph-mgr architecture](https://github.com/Tendrl/documentation/tree/master/images/ceph-mgr-arch.png)

## Few Facts

• The ceph-mgr PR is not yet merged with ceph baseline
• ceph-mgr is not meant to provision/create a cluster, rather its meant and comes in picture post cluster creation. So from tendrl point of view the storage node provisioning and cluster creation should happen as pre-requisite (using ceph-installer or ceph-ansible whatever the call is)
• ceph-mgr provides set of REST apis (which calamari-lite used to) as one protocol exposed to access ceph-mgr backend
• New protocols could be added in the form of python modules to avoid REST (if needed)
• ceph-mgr has got "ceph tell mgr" mechanism to send management commands to ceph-mgr

## Integrating tendrl with ceph-mgr

There are two options to get tendrl integrated with ceph-mgr, using REST apis or by adding a python module and invoking the same from ceph-bridge on the monitor nodes. The below block diagrams try to explain how ceph-mgr would fit in tendrl stack and utilized for management of a ceph cluster

**Option-1: tendrl using ceph-mgr REST apis way of integration**

![ceph-mgr architecture](https://github.com/Tendrl/documentation/tree/master/images/tendrl-ceph-mgr-rest.png)

**Option-2: tendrl using ceph-mgr python module way of integration**

![ceph-mgr architecture](https://github.com/Tendrl/documentation/tree/master/images/tendrl-ceph-mgr-python-mod.png)

## Analyzed REST APIs

There are certain differences from existing calamari-lite REST api in the format of output and also few apis are missing as well. ceph-mgr works on ceoncept of single cluster only for ceph so now there is no concept of /api/v2/cluster or /api/v2/cluster/<fsid> apis anymore.

### Existing apis with differences / issues from calamari-lite
- The api /api/v2/cluster/sync_object/health,fs_map,osd_map,mon_map,pg_summary,config always return 500 error
- There is no /api/v2/cluster so its not possible to get cluster-id from ceph-mgr
- There is a difference in output format of listing api of storage nodes of cluster

ceph-mgr: /api/v2/cluster/server

```
[
    {
        "hostname": "<FQDN name>",
        "ceph_version": "ceph version v0.70-29370-g0fe9231 (0fe92311d2ad412301e7e17f88d4eaef9ec6d2d6)",
        "services": [
            {
                "type": "mon",
                "id": "a"
            },
            {
                "type": "mds",
                "id": "a"
            },
            {
                "type": "osd",
                "id": "0"
            },
            {
                "type": "osd",
                "id": "1"
            },
            {
                "type": "osd",
                "id": "2"
            }
        ]
    }
]
```

calamari-lite: /api/v2/cluster/<fsid>/server

```
[
    {
        "fqdn": "<FQDN name>", 
        "hostname": "<name>", 
        "services": [
            {
                "fsid": "0c581569-ab59-4d6f-97da-313eb27e01be", 
                "type": "mon", 
                "id": "<id>", 
                "running": true
            }
        ], 
        "frontend_addr": "<IP>", 
        "backend_addr": null, 
        "frontend_iface": null, 
        "backend_iface": null, 
        "managed": true, 
        "last_contact": "2016-09-21T08:33:21.886334+00:00", 
        "boot_time": "1970-01-01T00:00:00+00:00", 
        "ceph_version": null
    }
]
```
- There is difference in output format of OSD listing apis
  ceph-mgr

```
[
    {
        "id": 0,
        "uuid": "9539aa28-8e36-40e3-af1b-3ad62337e23a",
        "up": true,
        "reweight": 1.0,
        "server": "<FQDN name>",
        "pools": [
            0,
            1,
            2
        ],
        "valid_commands": "('scrub', 'deep_scrub', 'repair')",
        "public_addr": "<IP>:6800/6595",
        "cluster_addr": "<IP>:6801/6595"
    }
]
```

calamari-lite: /api/v2/cluster/<fsid>/osd

```
[
    {
        "uuid": "712bd0d7-eb39-4fa9-bef5-0b39dd0f522e", 
        "up": true, 
        "in": true, 
        "id": 0, 
        "reweight": 1.0, 
        "server": "<FQDN name>", 
        "pools": [], 
        "valid_commands": [
            "scrub", 
            "deep_scrub", 
            "repair"
        ], 
        "public_addr": "<IP>:6800/25957", 
        "cluster_addr": "<IP>:6801/25957", 
        "crush_node_ancestry": [
            [
                -2, 
                -1
            ]
        ], 
        "backend_partition_path": "unknown", 
        "backend_device_node": "unknown", 
        "osd_data": "/var/lib/ceph/osd/mycluster-0", 
        "osd_journal": "/var/lib/ceph/osd/mycluster-0/journal"
    }
]
```
- /api/v2/cluster/crush_rule does not provide all the options which could be passed using ceph CLI

### Missing / Required apis

Below are few apis which would be required if tendrl decides to integrate with ceph-mgr using REST protocol
1. /api/v2/cluster to get the details like name and id of the cluster. Otherwise tendrl would always have to default the name to `ceph` and use randomly created UUID as cluster-id
2. /api/v2/cluster/mon/<mon id>/status as it was used in skyring to get additional status details of the monitor nodes
3. /api/v1/cluster/health_counters required for aggregating the object counts etc for the cluster (which gets reported in dashboards). _Not sure if `ceph tell mgr osd perf` could be used for this purpose. More analysis required._ 
   Note: I understand we were using old version of api, but somehow this detail is required and if ceph tell mgr help, well and good.
4. /api/v2/cluster/crush_node for creation of crush map while create cluster flow

## Missing framework components / items in ceph-mgr for tendrl
1. Need to write a python module from scratch to be consumed from tendrl's ceph-bridge (if option - 2 is used above for integration with tendrl). Detailed guidelines could be found at https://github.com/ceph/ceph/pull/10328/commits/6d90788da8b6b9f3effb2f2d12a3957783a72337 for adding new python module in ceph-mgr
2. Of course ceph-mgr should be available with ceph baseline :))

**Comment by shtripat** [comment]
I have added analysis details in above comment. @brainfunked @jcsp check if something missing or needs correction.
Also the images are sent as another PR https://github.com/Tendrl/documentation/pull/38. Once merged will correct the paths so that it shows the images properly.

**Comment by jcsp** [comment]
Here are some hopefully useful points:
- It's not correct to say that the mgr doesn't use the mon for getting the cluster maps.  That's actually exactly what it does do.  The mgr subscribes to the mon for map updates, and receives them whenever a map changes (using the same internal mechanism that ceph clients use to subscribe to the maps)
- "/api/v2/cluster/health_counters" never existed, you're talking about the v1 API.
- sync_object was just broken, I've fixed it now.  Same with missing 'in' attribute on OSDs
- crush_node was added to calamari after the version of the rest module that was used for ceph-mgr, it just needs porting forward from the relevant calamari branch.
- the /mon/<id>/status endpoint no longer makes sense, because we don't go and fetch out of band information from daemons' admin sockets any more.  ceph-mgr can't give you a "running" indication for daemons because all it knows is whether the daemon is communicating and part of the cluster, not whether it's running.  The rest module actually does have access to one daemon's "mon_status" data, which is used to populate the "in_quorum" and "leader" attributes on the /cluster/mon endpoint.  What is it that you're looking for from the old mon status?
- reporting the FSID and cluster name is obviously a pretty trivial thing for someone to add.

**Comment by shtripat** [comment]
@jcsp thanks for comments. I would update the details based on these comments.

**Comment by shtripat** [comment]
@jcsp  IIRC, regarding mon status api, we were using in skyring for getting leader state of the mon to mark in DB. If there is a way to figure out mon leader state that might suffice I feel.

**Comment by shtripat** [comment]
@jcsp Below are few questions raised regarding integration feasibility of ceph-mgr with tendrl. Tried replying based on my understanding but I would certainly seek your expert comments as well on these :)
1. Would be possible and if yes, more efficient, for the ceph mgr python module to act as the state bridge directly? This means that the module would translate the in-memory representation of ceph's state into tendrl's central store.
   
   > > Shubhendu: As I understand the python module done as another protocol to talk to ceph-mgr can have its own backend store. If that backend store could be etcd (tendrl's central store), I feel this python module could work as you expect here. @jcsp your coments?
2. How would the ceph mgr module keep updating tendrl (either directly into the central store or via some communication with the state bridge) about the updates in the cluster?
   
   > > Shubhendu: My understanding is that tendrl ceph-bridge to use ceph-mgr python module as protocol to talk to ceph cluster for truth values. And then the tendrl ceph-bridge updates the details in etcd.
   > > But if above option is feasible the python module itself can directly update details in etcd. @jcsp  ??
3. Is it possible to detect in-flight operations in a ceph cluster via manager?
   
   > > Shubhendu: If I understand it correctly, any command line execution on ceph cluster would be known to ceph-mgr and so it should be available to ceph-mgr. Comment @jcsp ?
4. Does the manager provide any functionality to act as a gateway through which operations could be invoked on the cluster?
   If there's no gateway functionality provided by ceph manager, would it mean that tendrl would need a separate operations bridge for ceph? How would this bridge invoke operations on the cluster?
   
   > > Shubhendu: Other than cluster creation, all other operations like pool creation/update/delete etc an be done at the moment using REST end points exposed. @jcsp correct me if wrong. If rbd management APIs as well are provided, it should be fine.

@brainfunked once discussed and clear, would add the details in above analysis document.

**Comment by jcsp** [comment]
As has been discussed before, yes, clearly you could embed your "bridge" as a python module in ceph-mgr, and then send whatever protocol (such as etcd writes) you wanted over the network.

I should point out though, that is is probably pointless to mirror the state of the ceph mon/mgr into an etcd cluster.  Remember that the mons themselves are a highly available cluster, you're not really getting any benefit by reading something out of ceph and writing it into etcd.

The question about "in flight operations": it depends what you mean.  If you mean things like individual mon commands, then no (these are all immediately-applied transactions so they don't have a concept of being in flight).  If you mean long running operatinos like in the rest module, then yes, although there is some work to do generalise that code to decouple the long running operations from the rest code.

As for invoking operations:
http://docs.ceph.com/docs/master/mgr/plugins/#sending-commands

Note that send_command is sending messages to the mons, it is not calling out to external CLI utilities.  So anything that's in an external tool is a different question.l

For doing rbd type operations your mgr module can just load librbd like any other python code would.
