### ISSUE TITLE
Document the design for create cluster workflow in tendrl

### ISSUE THREAD

**Issue by shtripat** [Tendrl/documentation#30]
Add documentation with details about create cluster workflow regarding what components are involved and how the data flows. This is important to tendrl as discovery of storage nodes, acceptance (bootstrapping) of storage nodes with full entity details like devices, CPUs etc is at core before a cluster creation can start. The points to keep in mind while design are
- How the storage nodes and if full inventory structure is discovered and known to tendrl
- How underlying storage layout is framed for ansible to submit to backend
- How public and cluster networks segregation is taken care
- Storage profiles consideration (applicable to ceph only may be)
- Async task framework and reporting details of specific steps to client code
- Storage node provisioning (installation of all required bits)
- Cluster provisioning (forming the full cluster layout at backend)

These are just few points and may be detailed while design detailing done.

**Comment by r0h4n** [comment]
Tendrl doesnt plan to support Create Cluster
