### ISSUE TITLE
Document the design for import cluster workflow

### ISSUE THREAD

**Issue by shtripat** [Tendrl/documentation#33]
Document the flow how import would get triggered from tendrl. The below steps should be detailed -
- How the existing cluster created using CLI gets known/discovered by tendrl
- What is procedure to trigger the import cluster flow (like select a bootstrap node and then get the whole details in tendrl central store)
- What details to be pulled and how to be maintained in tendrl central store
- How to make sure any changes from command line to the underlying cluster gets refelected in tendrl seamlessly

**Comment by brainfunked** [comment]
At a generic level, state bridges are pointed to the cluster they are to be responsible for, along with etcd connection details. The import process thereafter is strictly implementation specific depending upon the cluster and the bridge. However, there have to be some details to be added to the communication protocol to indicate that a cluster is still being imported or has finished being imported etc.

Keeping updated with the changes on the cluster is also implementation specific. This does not belong in the architecture documentation, but instead with the codebases of the bridges.

IAC, I'll keep this issue open till workflow and protocol documentation has been added, where the generic bits of this issue belong.
