### ISSUE TITLE
Preset criteria and guidelines for the frontend

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/documentation#41]
With respect to the [component diagram](https://github.com/Tendrl/documentation/blob/master/tendrl-core-components-overview.adoc), the frontend part needs expansion.

This is to enable the frontend team to make better choices to build the solution. Some high level criteria will help us align with the direction that we're all headed.

For example, limitations regarding:
- Dependencies
- Licenses
- Packaging
- Deployment
- Platforms
- User agent etc.

**Comment by cybernth** [comment]
@gnehapk Dependencies, Licenses  etc doesn't make much sense from an upstream perspective. 
Packaging : rpm packages, fedora koji and centos sig
Platforms :  Fedora, Centos(6&7)
UserAgents : Firefox and Chrome

**Comment by mbukatov** [comment]
Hmm, could you specify what kind of information are you missing from the component diagram? While it's clear that your team needs to know all the information you listed, I'm not sure all of them belongs to the diagram. I'm curious as I could see some ways to improve the diagram as well (https://github.com/Tendrl/documentation/issues/61). For example, would you like to have a web server or load balancer to be shown there?
