### ISSUE TITLE
Do Tendrl have mailing list and irc channel?

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/documentation#59]
I have some query regarding Tendrl(node_agent) and I am not able to reach out to you people can some please let me know your mailing list and Irc channel. So I can contact you people easily.

Sorry for creating this issue but I was not finding any other channel to ask this question.

Thanks

**Comment by mkudlej** [comment]
Please take a look at 
http://tendrl.org/community/

**Comment by mbukatov** [comment]
@r0h4n Do you think that it would make sense to add a link to tendrl.org site in the description of the github project?

**Comment by japplewhite** [comment]
Github profile at https://github.com/organizations/Tendrl/settings/profile was updated with http://tendrl.org site url
