### ISSUE TITLE
need more detail on etcd configuration

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/documentation#63]
we should include something like this in https://github.com/Tendrl/documentation/blob/master/deployment.adoc 

 
 You will need to edit the following options in /etc/etcd/etcd.conf and replace localhost with your node's IP address (10.0.2.15 in this example)
 ETCD_LISTEN_PEER_URLS="http://10.0.2.15:2380"
 ETCD_LISTEN_CLIENT_URLS="http://10.0.2.15:2379"
 ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.0.2.15:2380"
 ETCD_INITIAL_CLUSTER="default=http://10.0.2.15:2380"
 ETCD_ADVERTISE_CLIENT_URLS="http://10.0.2.15:2379"

**Comment by mbukatov** [comment]
Where do you have this information from?

**Comment by mbukatov** [comment]
@r0h4n Could we get clarification on this?

**Comment by mbukatov** [comment]
@fbalak I see that you use configure some of those options in https://github.com/Tendrl/usmqe-setup/blob/tendrl-setup/roles/etcd/tasks/main.yml , where did you get those values from? Did we get any ack from dev team for our configuration in the ansible role?

**Comment by r0h4n** [comment]
I think this (https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference) has solved above problem, closing this one, let me know if still required
