### ISSUE TITLE
Tendrl package(rpm) installation and setup instructions

### ISSUE THREAD

**Issue by cybernth** [Tendrl/documentation#68]
Create a doc which talks about installation and setup instructions for different components

**Comment by mbukatov** [comment]
From my point of view, we need to address https://github.com/Tendrl/specifications/issues/25 before going on with rpm installation instructions.

**Comment by mbukatov** [comment]
Another issue which needs to be resolved first is: https://github.com/Tendrl/node_agent/issues/99
