### ISSUE TITLE
HTTP verbs

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/documentation#70]
It seems that it is not clear how to use HTTP verbs in API. Now API uses HTTP verbs with API function names with verbs. For example in https://github.com/anivargi/documentation/blob/c26ccba15091efd70de41c54929f5f710626b8ec/api/ceph-pool-examples.adoc
is used HTTP verb **DELETE** and also **Delete** is used in function name. I think we should pick one way how to provide action:
1) use HTTP verbs
2) use POST and verb in function name

Also this should be cleared in https://github.com/Tendrl/documentation/blob/master/api/overview.adoc

Here you can find example of usage of HTTP verbs: https://github.com/ManageIQ/manageiq_docs/blob/master/api/overview/http.adoc#methods-and-related-urls

**Comment by julienlim** [comment]
@anivargi FYI.

**Comment by r0h4n** [comment]
@anivargi what are the updates for this?

**Comment by anivargi** [comment]
@r0h4n The issue is irrelevant now. We don't have any delete actions and also the API endpoints have been made consistent.
