### ISSUE TITLE
Unable to find appropriate IRC details for Tendrl

### ISSUE THREAD

**Issue by srijitamukherjee** [Tendrl/documentation#71]
Being a new contributor, I tried searching for a community communication methods, but found no IRC channels mentioned, nor could i find mailing list info.

**Comment by mbukatov** [comment]
Welcome, on [github page for Tendrl organization](https://github.com/Tendrl) there is a link to [tendrl.org](http://tendrl.org/) site, which is the main webpage of the project and [refers to the irc channel in it's community section](http://tendrl.org/community/):

> Find us on irc.freenode.net #tendrl-devel

**Comment by r0h4n** [comment]
@mbukatov I think the individual repos or atleast the Documentation repo should have mention to the IRC and mailing list info.

**Comment by mbukatov** [comment]
@r0h4n I have no problem with that. I guess it the best place would be a README file, because it's most visible.

**Comment by sankarshanmukhopadhyay** [comment]
I'll open up an issue to have a new-contributor-onboarding file added.
