### ISSUE TITLE
Documentation for time series database

### ISSUE THREAD

**Issue by fbalak** [Tendrl/documentation#76]
In https://github.com/Tendrl/performance-monitoring/blob/32bfd131150833d840e67b7904ad1721eb656667/doc/source/installation.rst is written that user should specify `time_series_db_server` and `time_series_db_port` in `performance-monitoring.conf.yaml` config file but there is no further mention about what it is. In documentation should be specified what is meant as a time series database for Tendrl (graphite).

**Comment by sankarshanmukhopadhyay** [comment]
@anmolbabu is it possible to update the documentation to reflect the observation as above?

**Comment by anmolbabu** [comment]
@sankarshanmukhopadhyay Sure

**Comment by sankarshanmukhopadhyay** [comment]
@fbalak please confirm that the changes to the document are sufficient or, whether further additions would be desired.

**Comment by fbalak** [comment]
@sankarshanmukhopadhyay It seems ok. I will try to install performance-monitoring according those instructions and if it will run well I will close the issue.

**Comment by fbalak** [comment]
Tested with tendrl-node-agent-1.2-02_24_2017_00_01_02.noarch. It seems ok. --> closing
