### ISSUE TITLE
Package installation reference sequence of steps need to be updated

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/documentation#77]
https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference

**Comment by mkudlej** [comment]
This document should be updated according https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.2.2

**Comment by r0h4n** [comment]
The latest release/install docs are here https://github.com/Tendrl/documentation/wiki/Tendrl-release-latest
