### ISSUE TITLE
tendrl-alerting documentation

### ISSUE THREAD

**Issue by fbalak** [Tendrl/documentation#79]
`tendrl-alerting` packages are available. Tendrl Package Installation Reference on wiki of Tendrl/documentation should be updated. There should be documented how to install and configure `tendrl-alerting` and on which servers it should run.

**Comment by anmolbabu** [comment]
@nthomas-redhat @r0h4n I have no permissions to edit or send PR to documentation wiki I have documented the alerting module installation steps @ https://github.com/Tendrl/alerting/blob/develop/doc/source/installation.rst

Can you please add this info to installation wiki

**Comment by sankarshanmukhopadhyay** [comment]
@anmolbabu the wiki permissions have been fixed. Could you update it now?

**Comment by anmolbabu** [comment]
@sankarshanmukhopadhyay Done... added the install instructions now... Thanks for the permissions...

@fbalak The installation steps have been added to the wiki.
Please close this if not relevant anymore..

**Comment by fbalak** [comment]
Looks ok.
