### ISSUE TITLE
node-agent installation, cluster creation order

### ISSUE THREAD

**Issue by fbalak** [Tendrl/documentation#83]
There needs to be created a cluster before node-agent is installed so it can be imported into Tendrl. Cluster import job may fail if cluster is created after node-agent is installed. This should be documented.

@r0h4n Is this correct?

**Comment by mbukatov** [comment]
I'm not sure if this behavior is correct wrt expected use cases and proposed features. @fbalak do we have an issue for this aspect of this?

Edit: I have created the issue: https://github.com/Tendrl/node-agent/issues/467
