### ISSUE TITLE
Changing user and developer communication channels to Gitter

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/documentation#86]
At present the team members use a combination of IRC, Slack (a private instance) etc to communicate and collaborate. It would be good to cut over completely to Gitter - the advantages of push notifications are maintained along with browser based entry point.

https://gitter.im/Tendrl/tendrl-devel and https://gitter.im/Tendrl/tendrl-users are already set up. @Tendrl/tendrl-core

**Comment by r0h4n** [comment]
Ack, This looks good
