### ISSUE TITLE
Confusing Step in Tendrl-Package-Installation-Reference(Revised)

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/documentation#91]
In https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference(Revised) under step 7, we have asked user to input graphite_port and graphite_host which can be confuding to a new user as in none of the above steps we have mentioned where user have installed graphite.

This section of step can be added after installing monitoring-integration which is setting up graphite

**Comment by mbukatov** [comment]
Or we could point out that the host is the same as etcd server and as the machine we are installing node agent on in this step. At least that's what is implied in the guide right now: all these steps are part of section tendrl server. And we should not forget to note that graphite is configured later in this section.

**Comment by mbukatov** [comment]
I tried to address this in this commit:

https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference(Revised)/_compare/23025e47a3abb20aca3c59fe538ccdb75be1457e...60b922335260dc082edb88ced7c966ee60e38605

**Comment by mbukatov** [comment]
@rishubhjain please review the current state of the docs and provide feedback (suggestions, other problem I created when solving this one) or close this issue, thank you

**Comment by rishubhjain** [comment]
@mbukatov I guess the issue is resolved, can I close this issue?

**Comment by mbukatov** [comment]
@rishubhjain if you agree with the solution, then yes, feel free to close it

**Comment by rishubhjain** [comment]
@mbukatov @nthomas-redhat has made the necessary changes, I am closing the issue
