### ISSUE TITLE
Gluster version

### ISSUE THREAD

**Issue by fbalak** [Tendrl/documentation#93]
Is there somewhere specified gluster version? I am using [nightly builds](http://artifacts.ci.centos.org/gluster/nightly/master/7/x86_64/) which works but with version 3.9 the import cluster job times out and fails. Gluster version should be mentioned in [instalaltion guide](https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference)

**Comment by r0h4n** [comment]
This is fixed  https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.2-(install-guide)

see "Supported SDS" section
