### ISSUE TITLE
grafana installation not mentioned in install-guide 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [Tendrl/documentation#95]
yum install tendrl-monitoring-integration fails saying grafana required.

logs:
> yum install tendrl-monitoring-integration
> ---> Package tendrl-monitoring-integration.noarch 0:1.5.4-2.el7.centos will be installed
> --> Processing Dependency: grafana < 4.5.3 for package: tendrl-monitoring-integration-1.5.4-2.el7.centos.noarch
> --> Processing Dependency: grafana >= 4.5.2 for package: tendrl-monitoring-integration-1.5.4-2.el7.centos.noarch
> --> Finished Dependency Resolution
> Error: Package: tendrl-monitoring-integration-1.5.4-2.el7.centos.noarch (tendrl-release)
>            Requires: grafana >= 4.5.2
> Error: Package: tendrl-monitoring-integration-1.5.4-2.el7.centos.noarch (tendrl-release)
>            Requires: grafana < 4.5.3
> Error: Package: tendrl-grafana-plugins-1.5.4-2.el7.centos.noarch (tendrl-release)
>            Requires: grafana
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> 

But, [install guide](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.1-(install-guide)) does not mention about installing grafana . 

Also, a specific version of grafana needs to be installed (>=4.5.2 and <4.5.3).

Please update this info. in the install guide.

**Comment by r0h4n** [comment]
The install guide mentioned in your comment is for tendrl-release 1.5.1

Please check the latest version
https://github.com/Tendrl/documentation/wiki/Tendrl-release-latest#tendrl-server-installation

Grafana details are mentioned.
