### ISSUE TITLE
Job type reload is not applicable for unit rsyslog.service

### ISSUE THREAD

**Issue by fbalak** [Tendrl/documentation#97]
In [documentation](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.5-(install-guide)) is stated that on tendrl-server and gluster nodes should be called:
```
systemctl reload rsyslog
```
but the command returns:
```
Failed to reload rsyslog.service: Job type reload is not applicable for unit rsyslog.service.
See system logs and 'systemctl status rsyslog.service' for details.
```
It seems that this service doesn't support `reload` action.

Tested on:
```
CentOS Linux release 7.4.1708 (Core)
```

CC: @mbukatov

**Comment by cybernth** [comment]
Use restart instead of reload as it is not supported. Updated the docs
